
[build]
  base = "."
  publish = "client/dist"
  command = "npm install && cd client && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
