
[build]
  # O comando agora entra na pasta 'client' primeiro.
  command = "cd client && npm install && npm run build"
  # O diretório de publicação é relativo à pasta 'client'.
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
